name: 'AutoYAPF'
author: 'Kaustubh Sonawane'
description: 'Format Python code using YAPF'
inputs:
  args:
    description: 'Arguments for YAPF'
    required: true
    default: '--help'
outputs:
  exit-code:
    description: 'Output by yapy'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}